name: Test
on: [ push, pull_request ]
env:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2 
    -Dorg.slf4j.simpleLogger.showDateTime=true 
    -Djava.awt.headless=true
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
jobs:
  test:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        distribution: [ 'temurin', 'corretto' ]
        version: [ '8', '11', '17', '21' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build
        run: mvn -B -ntp --errors --fail-at-end --show-version -DskipTests install
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.version }}
      - name: Test
        run: mvn -B -ntp -errors -pl :galette-integration-tests install
        shell: bash